### ISSUE TITLE
Is there a way to disable dithering?

### ISSUE THREAD

**Issue by Des-Nerger** [shabbyrobe/wu2quant#1]

**Comment by shabbyrobe** [comment]
Not at the moment, though I will hopefully try to find a way to add that to the algo itself at some stage.

You could instead use one of the functions that extracts just the quantised palette, i.e. `Quantize()` or `QuantizeRGBAToPalette()`, then do the conversion yourself using `color.Palette.Convert()`. This isn't exactly fast as it calculates the Euclidean distance manually for every single pixel lookup, but it works, and there are data structures you can use to make it faster if need be:

```go
var img *image.RGBA
pal := make(color.Palette, 0, 16)
pal = q.Quantize(pal, img)

for y := 0; y < img.Bounds().Dy(); y++ {
	for x := 0; x < img.Bounds().Dx(); x++ {
		img.Set(x, y, pal.Convert(img.At(x, y)))
	}
}
```

Using `ToPaletted()`:

![0](https://user-images.githubusercontent.com/288426/149417930-a03c7b25-17bb-403e-9d40-350bdce23f68.png)

Using the example provided:

![1](https://user-images.githubusercontent.com/288426/149417957-d1f2d58c-859f-4d59-9d0a-bbfc66573df2.png)

I have added this to `tool.go` behind the `-dither=false` flag.

**Comment by Des-Nerger** [comment]
Oh, I may get it a bit confused.
By "dithering" I had in mind the `.png`'s used in `README.md` from the `demo` directory, like this one:
![](https://github.com/shabbyrobe/wu2quant/blob/main/demo/kodimg23-0006.png?raw=true)
I thought it is how this library always works and didn't find any mentions of "dither" in the code... But it seems `tool.go` wouldn't do any(thing I would call) dithering in the first place! Its output, whether with this newly added `-dither=false` option or without it, doesn't produce those dots that `/demo/*png` examples have. The images look like generated differently from the way `tool.go` does it. Where does their dithering come from, then, I wonder 🤔?

**Comment by shabbyrobe** [comment]
Ah of course, the dithering will be from the fact that it's an animated gif! My first presumption was that there was some quirk in the way the wu2 quantiser calculates the colour to replace with during quantisation, or perhaps it might've been doing a little bit of error correction that I hadn't noticed. I will replace those demos in the readme. Thank you for bringing it to my attention.

**Comment by shabbyrobe** [comment]
Hope you don't mind me reopening this; it is actually something for me to action and I'd like to keep the reminder around.
